---
title: "Marcel_Method"
author: "Alex Walker"
date: "16/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(tidyverse) 
library(here) 
library(readxl) 
library(knitr)
library(kableExtra)
library(rmarkdown)

season_1516 <- read_csv(here("data","1516_season.csv"))
season_1617 <- read_csv(here("data","1617_season.csv"))
season_1718 <- read_csv(here("data","1718_season.csv"))
season_1819 <- read_csv(here("data","1819_season.csv"))
season_1920 <- read_csv(here("data","1920_season.csv"))

season_1516$season <- c(2016)
season_1617$season <- c(2017)
season_1718$season <- c(2018)
season_1819$season <- c(2019)
season_1920$season <- c(2020)

pred_year = 2021 #this is the season in which we're trying to forecast the players stats

n3 = pred_year-3
n2 = pred_year-2
n1 = pred_year-1


#Load in the seasons you'll be using and add in the season var. Using the ns will allow us to automate steps in the future

##Things to note: In order to complete Marcel projections I need 1) Season weights (I'm sticking with 5/4/3) 2) I'll need to find each players average in the relevant seasons 3) I'll need to find the league average for F/D in each category 4) Regress the player using the league average at their position 5) Determine their projected TOI 6) Apply age adjustment 7) adjust based on 2020 baseline


#Finding the league averages for the stats we're going to use is the first order of business: 


lg_avg_n1 <- season_1920 %>%
          mutate(Pos = replace(Pos, Pos != "D", "F")) %>%
          filter(GP >= 15) %>%
          group_by(Pos) %>%
          summarize(
          season = n1,
          lg_avg_gp = mean(GP, na.rm = TRUE),
        lg_avg_g = mean(G, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_a = mean(A, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_pts = mean(PTS, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_ppg = mean(PPG, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_ppa = mean(PPA, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_s = mean(S, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_blk = mean(BLK, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_hit = mean(HIT, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_pim = mean(PIM, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_fow = mean(FOW, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_fol = mean(FOL, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_toi = mean(TOI, na.rm = TRUE)/mean(GP, na.rm = TRUE),
         )

lg_avg_n2 <- season_1819 %>%
          mutate(Pos = replace(Pos, Pos != "D", "F")) %>%
           filter(GP >= 15) %>%
          group_by(Pos) %>%
          summarize(
          season = n2,
        lg_avg_gp = mean(GP, na.rm = TRUE),
        lg_avg_g = mean(G, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_a = mean(A, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_pts = mean(PTS, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_ppg = mean(PPG, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_ppa = mean(PPA, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_s = mean(S, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_blk = mean(BLK, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_hit = mean(HIT, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_pim = mean(PIM, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_fow = mean(FOW, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_fol = mean(FOL, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_toi = mean(TOI, na.rm = TRUE)/mean(GP, na.rm = TRUE),
          )


lg_avg_n3 <- season_1718 %>%
          mutate(Pos = replace(Pos, Pos != "D", "F")) %>%
           filter(GP >= 15) %>%
          group_by(Pos) %>%
          summarize(
          season = n3, 
          lg_avg_gp = mean(GP, na.rm = TRUE),
        lg_avg_g = mean(G, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_a = mean(A, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_pts = mean(PTS, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_ppg = mean(PPG, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_ppa = mean(PPA, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_s = mean(S, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_blk = mean(BLK, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_hit = mean(HIT, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_pim = mean(PIM, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_fow = mean(FOW, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_fol = mean(FOL, na.rm = TRUE)/mean(TOI, na.rm = TRUE),
        lg_avg_toi = mean(TOI, na.rm = TRUE)/mean(GP, na.rm = TRUE),
          )

#Now we combine the lg_avg stats to make one nice table. 

lg_avg_merg1 <- merge(lg_avg_n3, lg_avg_n2, by = intersect(names(lg_avg_n3), names(lg_avg_n2)), all = TRUE)

lg_avg_cmb <- merge(lg_avg_merg1, lg_avg_n1, by = intersect(names(lg_avg_merg1), names(lg_avg_n1)), all = TRUE)

## Finding each players rate stats

plyr_rt_n1 <- season_1920 %>%
            mutate(Pos = ifelse(Pos != "D", "F", "D")) %>%
             filter(GP >= 15) %>%
          group_by(Pos) %>%
          summarize(
          player = Player,
          age = Age, 
          season = n1,
          gp = GP, 
          g = G/GP, 
          a = A/GP,
          pts = PTS/GP,
          ppg = PPG/GP,
          ppa = PPA/GP,
          s = S/GP,
          blk = BLK/GP,
          hit = HIT/GP,
          pim = PIM/GP,
          fow = FOW/GP,
          hit = HIT/GP,
          pim = PIM/GP,
          fow = FOW/GP,
          fol = FOL/GP,
          toi_gp = TOI/GP,
          )

plyr_rt_n2 <- season_1819 %>%
            mutate(Pos = ifelse(Pos != "D", "F", "D")) %>%
             filter(GP >= 15) %>%
          group_by(Pos) %>%
          summarize(
          player = Player,
          age = Age, 
          season = n2,
          gp = GP, 
          g = G/GP, 
          a = A/GP,
          pts = PTS/GP,
          ppg = PPG/GP,
          ppa = PPA/GP,
          s = S/GP,
          blk = BLK/GP,
          hit = HIT/GP,
          pim = PIM/GP,
          fow = FOW/GP,
          hit = HIT/GP,
          pim = PIM/GP,
          fow = FOW/GP,
          fol = FOL/GP,
          toi_gp = TOI/GP,
          )

plyr_rt_n3 <- season_1718 %>%
            mutate(Pos = ifelse(Pos != "D", "F", "D")) %>%
             filter(GP >= 15) %>%
          group_by(Pos) %>%
          summarize(
          player = Player,
          age = Age, 
          season = n3,
          gp = GP, 
          g = G/GP, 
          a = A/GP,
          pts = PTS/GP,
          ppg = PPG/GP,
          ppa = PPA/GP,
          s = S/GP,
          blk = BLK/GP,
          hit = HIT/GP,
          pim = PIM/GP,
          fow = FOW/GP,
          hit = HIT/GP,
          pim = PIM/GP,
          fow = FOW/GP,
          fol = FOL/GP,
          toi_gp = TOI/GP,
          )

# Join the seasons together. In this case I used the merge function twice. 

plyr_merge1 <- merge(plyr_rt_n3, plyr_rt_n2, by = intersect(names(plyr_rt_n3), names(plyr_rt_n2)), all = TRUE)

plyr_rt_cmb <- merge(plyr_merge1, plyr_rt_n1, by = intersect(names(plyr_merge1), names(plyr_rt_n1)), all = TRUE)

#insert the weights = (5 4 3) into the df. 

plyr_rt_cmb$weights = with(plyr_rt_cmb, ifelse(season == n1,5, ifelse(season == n2, 4, 3)))

weighted_stats <- plyr_rt_cmb %>%
                mutate_at(vars(c("gp", "g", "a", "pts", "ppg", "ppa", "s", "blk", "hit", "pim", "fow", "fol")), ~.*weights) %>%
                 mutate(toi_weight = toi_gp*weights) %>%
                 mutate(proj_toi = case_when((Pos == "F" & season == n2) ~ 0.20 * toi_gp,
                                    (Pos == "F" & season == n1) ~ 0.64 * toi_gp + (200/82),
                                    (Pos == "D" & season == n2) ~ 0.20 * toi_gp,
                                    (Pos == "D" & season == n1) ~ 0.64 * toi_gp + (250/82),
                                    TRUE ~ 0.00))
                
#Combine the 2 sets of data, weighted stats and the lg averages. We'll also adjust the age of the players to their age for the 2021 season.

combined_set <- merge(x = weighted_stats, y = lg_avg_cmb, by = c("season","Pos"))

combined_set_exp <- combined_set %>%
                        mutate(age = ifelse(season == n3, age + 3, ifelse(season == n2, age + 2, age +1))) 


sum_plyr <- combined_set_exp %>%             
                group_by(player, Pos) %>%
                summarize(
                  age = max(age),
                  sum_g = sum(g),
                  sum_a = sum(a),
                  sum_pts = sum(pts),
                  sum_ppg = sum(ppg),
                  sum_ppa = sum(ppa),
                  sum_s = sum(s),
                  sum_blk = sum(blk),
                  sum_hit = sum(hit),       
                  sum_pim = sum(pim),
                  sum_fow = sum(fow),
                  sum_fol = sum(fol),
                  sum_toi_gp = sum(toi_gp),
                  sum_wtoi = sum(toi_weight),
                  sum_projtoi = round(sum(proj_toi), digits = 2),
                  sum_lg_avg_g = sum(lg_avg_g),
                  sum_lg_avg_a = sum(lg_avg_a),
                  sum_lg_avg_pts = sum(lg_avg_pts),
                  sum_lg_avg_ppg = sum(lg_avg_ppg),
                  sum_lg_avg_ppa = sum(lg_avg_ppa),
                  sum_lg_avg_s = sum(lg_avg_s),
                  sum_lg_avg_blk = sum(lg_avg_blk),
                  sum_lg_avg_hit = sum(lg_avg_hit),
                  sum_lg_avg_pim = sum(lg_avg_pim),
                  sum_lg_avg_fow = sum(lg_avg_fow),
                  sum_lg_avg_fol = sum(lg_avg_fol),
                  sum_lg_avg_toi = sum(lg_avg_fol)) 
                  

#With sum_plyr made. We need to combine the summed numbers. 

f = (2000/82) 
d = (2750/82) #this is the amount of toi that will regress the players production towards their positions average

proj_plyr <- sum_plyr %>% mutate(proj_g = ((((sum_lg_avg_g/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_g)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82) %>%
                      mutate(proj_a = ((((sum_lg_avg_a/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_a)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82) %>%
                      mutate(proj_pts = ((((sum_lg_avg_pts/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_pts)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82) %>%
                      mutate(proj_ppg = ((((sum_lg_avg_ppg/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_ppg)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82) %>%
                      mutate(proj_ppa = ((((sum_lg_avg_ppa/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_ppa)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82) %>%
                      mutate(proj_s = ((((sum_lg_avg_s/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_s)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82) %>%
                      mutate(proj_blk = ((((sum_lg_avg_blk/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_blk)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82) %>%
                      mutate(proj_hit = ((((sum_lg_avg_hit/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_hit)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82) %>%
                      mutate(proj_pim = ((((sum_lg_avg_pim/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_pim)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82) %>%
                      mutate(proj_fow = ((((sum_lg_avg_fow/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_fow)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82) %>%
                      mutate(proj_fol = ((((sum_lg_avg_fol/sum_wtoi)*ifelse(Pos == "F",f,d))+sum_fol)/(ifelse(Pos == "F",f,d)+sum_wtoi))*sum_projtoi*82)
                
#using the toi from above we can now complete the forecast, the only remaining step is the age adjustment. The basic formula above is: 
#((sum_lg_avg_X/sum_wtoi*(f or d))+sum_X)/((f or d)+sum_wtoi) this gives us the players stat on a per minute basis. Multiply by proj_toi to get a per game rate and then by 82 to get a full season rate.

proj_stat_age <-proj_plyr %>% mutate_at(vars(starts_with("proj")), ~.*(ifelse(age <= 28, (28 - age)*0.01, (28-age)*0.005)+1))

#Basic age adjustment. Increased the amount but kept the ratio between the two the same.

projections21 <- proj_stat_age %>% summarize(
        player = player,
        Pos = Pos,
        age = age,
          toi = sum_projtoi,
          G = proj_g,
          A = proj_a,
          pts = proj_pts,
          ppg = proj_ppg,
          ppa = proj_ppa,
          ppp = proj_ppa+proj_ppg,
          sog = proj_s,
          blk = proj_blk,
          hit = proj_hit,
          pim = proj_pim,
          fow = proj_fow,
          hit = proj_hit,
          fow = proj_fow,
          fol = proj_fol)
          

write.csv(projections19, file = "C:\\Users\\Me\\Documents\\R\\Github\\Repos\\Marcel_Method_Hockey_2021\\Marcel_proj21.csv", row.names = FALSE)